spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.109:5432/
    username: postgres1
    password: postgres1
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /accounts
  port: 8081