spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
      fail-fast: false
  profiles:
    active: native
  security:
    user:
      password: admin

server:
  port: 8001